### ISSUE TITLE
commit ne dela

### ISSUE THREAD

**Issue by jonagricar** [jonagricar/APPR-2017-18#1]
Zdravo,
hotela sem narediti commit na projektu, da bi vam lahko zastavila vprašanje glede kode. Ko v desnem zgornjem kotu v R kliknem na git se spodaj samo vrti in nalaga, prav tako če odprem okno commit, poleg pa dobim še obvestilo directory name is invalid. Kaj lahko storim?

**Comment by jonagricar** [comment]
![brez naslova](https://user-images.githubusercontent.com/33510624/33796496-ab94f11c-dcf5-11e7-9f53-931d9d148cec.png)

**Comment by jonagricar** [comment]
če v konzolo vpišem getwd() mi vrne:
[1] "C:/Users/Jona Gričar/Documents/APPR-2017-18"

Hvala za pomoč!

**Comment by jaanos** [comment]
Problem je najbrž ta, da imaš v poti do projekta šumnike. Poskusi premakniti celoten projekt npr. pod C:\ (ali pa kam drugam).

**Comment by jonagricar** [comment]
Deluje, hvala za pomoč!

**Comment by jaanos** [comment]
Ko razrešiš zadevo, jo lahko zapreš - klikni na gumb **Close issue** (ali **Close and comment**, če obenem še kaj napišeš). Zadeve lahko zapiraš tudi iz commitov - če v sporočilo ob commitu, ki razreši zadevo, napišeš *Closes #1* (kjer #1 nadomestiš s številko zadeve), se bo zadeva zaprla, ko commit pushaš na GitHub.
