### ISSUE TITLE
tabela narodi2

### ISSUE THREAD

**Issue by jonagricar** [jonagricar/APPR-2017-18#3]
Zanima me, kako bi uredila, da bo R razumel rang kot število in mi potem v tabeli narodi2 uredil najprej po rangu in potem po spolu. Tabela je narejena vendar so rangi pomešani, jaz pa bi rada da si sledijo po vrsti?

Še eno vprašanje: kam pišemo kodo za ustvarjanje grafov, gre to tudi v uvoz ali kam drugam?
Hvala za odgovor in lepe praznike!

**Comment by jaanos** [comment]
Pri meni `arrange(rang, spol)` lepo uredi range po vrsti - vidim, da si jih tudi že pretvorila v števila, tako da mi ni jasno, zakaj bi se drugače uredili.

Sicer pa, namesto, da ročno delaš razpredelnice za vsak spol posebej in jih združuješ, raje uporabi funkcijo `melt`, ki podatke spravi v pravo obliko. Stolpec `rang` pravzaprav ne sodi v podatke, saj gre enostavno za razvrstitev po skupnem številu zmag, ki jih pa lahko dobiš s seštevanjem zmag po spolih (tako tudi razpredelnice `narodi1` ne potrebuješ). Razpredelnico `narodi2` lahko potem dobiš tako:
```R
narodi2 <- narodi %>% select(-rang, -zmage) %>% melt(id.vars = "drzava", variable.name = "spol",
                                                     value.name = "zmage") %>%
  mutate(zmage = parse_number(zmage, na = "–")) %>% drop_na(zmage) %>% arrange(spol, desc(zmage))
```
Za funkcijo `drop_na` bo treba uvoziti knjižnico ˙tidyr˙. Pri `parse_number` je za parameter `na` podan dolgi pomišljaj - če bi imela zaradi tega težave, lahko ta parameter izpustiš (še vedno bo delovalo, le nekaj opozoril se bo pojavilo). `arrange` na koncu uredi najprej po spolu, nato pa še padajoče po zmagah - seveda lahko to tudi spremeniš (ali pa sploh ne urejaš, ker urejenost podatkov za samo delo ni pomembna).

Kako si organizirate svoj projekt, je načeloma vaša stvar. Grafi se lahko rišejo neposredno v poročilo, lahko pa bi se pripravili npr. v `vizualizacija.r` (tj., shranili v spremenljivko) in potem prikazali na želenem mestu v poročilu.

**Comment by jonagricar** [comment]
sem naredila s funkcijo melt, da je vse skupaj krajše, hvala. grafe pa bom poskusila pripraviti v vizualizacija.r
