### ISSUE TITLE
zemljevid

### ISSUE THREAD

**Issue by jonagricar** [jonagricar/APPR-2017-18#4]
Na vajah sem hotela narisati zemljevid, vendar mi javlja napako iz slike. Kaj bi lahko bilo narobe? In še to, na zemljevidu bom označila države, iz katerih prihajajo zmagovalci; ali pustim sliko celega sveta ali obdržim samo ZDA in Kanado ter Evropo in ali se to sploh da narediti?

**Comment by jonagricar** [comment]
![brez naslova](https://user-images.githubusercontent.com/33510624/34556246-e9b7a1c0-f135-11e7-92fb-9895cbc6c4fa.png)

**Comment by jaanos** [comment]
Očitno ti sistem ne dovoli ustvarjanja mape `zemljevidi` neposredno na `C:\`. Ena možnost bi bila, da to mapo ustvariš ročno; lahko pa celotno mapo projekta premakneš nekam, kjer imaš pravico pisanja (glede na #1 pazi, da v poti ni šumnikov).

**Comment by jonagricar** [comment]
Zdaj, ko mi računalnik pusti ustvarjanje zemljevida me zanima kako bi naredila zemljevid iz tabele zmagovalci. Rada bi, da se seštejejo države da bi se videlo da je v eni državi v vseh teh sezonah bilo več zmagovalcev in potem glede na to obarva zemljevid.
Pa še to, zakaj mi v tabeli zmagovalci v 8.vrstici pri Michele Jacot v imenu da ? namesto črke e?

**Comment by jonagricar** [comment]
![rstudio](https://user-images.githubusercontent.com/33510624/34957851-98b49b90-fa2f-11e7-8efe-4faa77e4a349.png)

**Comment by jaanos** [comment]
Glede na to, da imaš v podatkih le države iz Evrope in Severne Amerike, lahko zemljevid že pri uvozu omejiš le na te:
```R
zemljevid <- uvozi.zemljevid("http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_countries.zip",
                             "ne_50m_admin_0_countries", encoding = "UTF-8") %>%
  pretvori.zemljevid() %>% filter(CONTINENT %in% c("Europe", "North America"))
```
Potem lahko z `group_by` in `summarise` prešteješ pojavitve vsake države (funkcija `n()`) in prikažeš na zemljevidu, ki mu omejiš prikazano območje, npr.
```R
zem.zmagovalci <- ggplot() + geom_polygon(data = zmagovalci %>% group_by(narodnost) %>%
                                            summarise(stevilo = n()) %>%
                                            right_join(zemljevid, by = c("narodnost" = "NAME_LONG")),
                                          aes(x = long, y = lat, group = group, fill = stevilo)) +
  coord_cartesian(xlim = c(-80, 22), ylim = c(37, 70))
```

Glede vprašaja v podatkih je problem v tem, da je dejanski znak `è`. Očitno pride do nekakšne napake pri pretvorbi znakov v sistemsko kodno tabelo (pri meni namreč pravilno prikaže). Lahko poskusiš v funkciji `uvozi.smucarje2` k `read_html` dodati še parameter `encoding = "UTF-8"`. Če vseeno ne bi delovalo, poskusi izrisati en enostaven graf:
```R
ggplot(zmagovalci %>% filter(spol == "Z", narodnost == "France"), aes(x = zmagovalec)) + geom_bar()
```
Če se na grafu ime pravilno izpiše, potem bi svetoval, da pustiš, kot je.

**Comment by jonagricar** [comment]
Oziroma je morda bolje, da naredim 2 zemljevida?
-iz tabele narodi sestejem koliko zmag ima posamezna drzava in potem to tudi sencim na zemljevidu glede na to koliko jih ima
-iz tabele prizorisca izberem drzave v katerih so bile tekme pokala(ali se to sploh da glede na to da so drzave zapisane kot kratice)

**Comment by jonagricar** [comment]
Ali je dovolj kar to kar sem mislila na zacetku?

**Comment by jonagricar** [comment]
Glede na to, da sem izrisala zemljevid zmagovalcev in izgleda super, bi morda dobro izpadel tudi zemljevid s prizorisci(1), ker bi dejansko imela oznacene drzave po celem svetu, brez ponovitev - le obarvane tiste v katerih so bile tekme?

**Comment by jaanos** [comment]
Lahko seveda narediš dva zemljevida - princip bo pri obeh podoben.
