### ISSUE TITLE
Poročilo

### ISSUE THREAD

**Issue by jonagricar** [jonagricar/APPR-2017-18#6]
Pozdravljeni, mislim, da sem dokončala poročilo in me zanima, če je treba še kaj popraviti. Videla sem, da mi pri repozitoriju piše 3 commits behind jaanos in me zanima, če moram narediti še pull, da bo res tako kot mora biti?
Ko sem ta teden hotela zagnati poročilo mi 3 tabele niso delovale, ker je nekdo spreminjal kodo na Wikipediji in sem morala spremeniti 3 vrstne rede pri uvozu (npr wikitable je bil [1] ne več [6]). Zdaj, ko sem popravila mi vse deluje a me skrbi, da ne bo spet kdo kaj popravljal Wikipedije in  da mi med ocenjevanjem ne bo hotelo prevesti poročila. Pri tem ne morem nič?
Lep pozdrav

**Comment by jaanos** [comment]
Poročila mi ne prevede, ker na repozitoriju ni datoteke `stenmark.jpg`. Problem je v vrstici `*.jpg` v datoteki `.gitignore` - če jo odstraniš, boš sliko lahko dodala v commit in naložila na repozitorij.

To, da je tvoj repozitorij 3 commite za mojim, je posledica tega, da sem naknadno (po tem, ko si naredila svoj fork) dodal te 3 commite. Ti so mišljeni za prihodnost in niso nujno potrebni za delovanje tvojega projekta. 

Kar se tiče uvoza iz Wikipedije, je ena možnost, da si spletne strani  shraniš v datoteke in iz njih uvažaš. Glede na to, da nimaš Shinyja, pa si lahko vnaprej pripraviš poročilo v obliki HTML in tega pokažeš, če bi se pojavili kakršnikoli problemi.

**Comment by jonagricar** [comment]
Sem popravila, mislim, da sedaj vse deluje tako kot mora.
Kako si lahko vnaprej pripravim HTML verzijo?

**Comment by jaanos** [comment]
V redu, bom dodal povezavo na repozitorij za zagovore, tako da se lahko z @alenFMF domeniš za termin zagovora. Če boš še kaj spreminjala, mi prosim javi, da posodobim povezavo.

Ko prevedeš poročilo s *Knit*, se ti prikazano poročilo shrani v datoteko `projekt.html` - to si lahko skopiraš nekam drugam, da ti je morebitno neuspešno prevajanje ne bo povozilo.
